config/routes.rb
Rails.application.routes.draw do
  resources :termins do
    collection do
      get :check
    end
  end
  resources :anwesenheitslistes
  resources :fehlzeits
  resources :veranstaltungs
  resources :moduls
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  # Defines the root path route ("/")
  root "termins#index"
  get 'pages/home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/anwesenheitsliste.rb
class Anwesenheitsliste < ApplicationRecord
  belongs_to :veranstaltung
  has_many :anwesenheitslisten_users
  has_many :users, through: :anwesenheitslisten_users
end

app/controllers/anwesenheitslistes_controller.rb
class AnwesenheitslistesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_anwesenheitsliste, only: %i[ show edit update destroy ]

  # GET /anwesenheitslistes or /anwesenheitslistes.json
  def index
    @anwesenheitslistes = Anwesenheitsliste.all
  end

  # GET /anwesenheitslistes/1 or /anwesenheitslistes/1.json
  def show
  end

  # GET /anwesenheitslistes/new
  def new
    @anwesenheitsliste = Anwesenheitsliste.new
  end

  # GET /anwesenheitslistes/1/edit
  def edit
  end

  # POST /anwesenheitslistes or /anwesenheitslistes.json
  def create
    @anwesenheitsliste = Anwesenheitsliste.new(anwesenheitsliste_params)

    respond_to do |format|
      if @anwesenheitsliste.save
        format.html { redirect_to anwesenheitsliste_url(@anwesenheitsliste), notice: "Anwesenheitsliste was successfully created." }
        format.json { render :show, status: :created, location: @anwesenheitsliste }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anwesenheitsliste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anwesenheitslistes/1 or /anwesenheitslistes/1.json
  def update
    respond_to do |format|
      if @anwesenheitsliste.update(anwesenheitsliste_params)
        format.html { redirect_to anwesenheitsliste_url(@anwesenheitsliste), notice: "Anwesenheitsliste was successfully updated." }
        format.json { render :show, status: :ok, location: @anwesenheitsliste }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anwesenheitsliste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anwesenheitslistes/1 or /anwesenheitslistes/1.json
  def destroy
    @anwesenheitsliste.destroy!

    respond_to do |format|
      format.html { redirect_to anwesenheitslistes_url, notice: "Anwesenheitsliste was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anwesenheitsliste
      @anwesenheitsliste = Anwesenheitsliste.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anwesenheitsliste_params
      params.require(:anwesenheitsliste).permit(:veranstaltung_id, :datum)
    end
end

app/helpers/anwesenheitslistes_helper.rb
module AnwesenheitslistesHelper
end

app/views/anwesenheitslistes/_anwesenheitsliste.html.erb
<div id="<%= dom_id anwesenheitsliste %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Veranstaltung:</strong>
    <%= anwesenheitsliste.veranstaltung_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Datum:</strong>
    <%= anwesenheitsliste.datum %>
  </p>

</div>

app/views/anwesenheitslistes/_form.html.erb
<%= form_with(model: anwesenheitsliste, class: "contents") do |form| %>
  <% if anwesenheitsliste.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(anwesenheitsliste.errors.count, "error") %> prohibited this anwesenheitsliste from being saved:</h2>

      <ul>
        <% anwesenheitsliste.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :veranstaltung_id %>
    <%= form.text_field :veranstaltung_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :datum %>
    <%= form.datetime_field :datum, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/anwesenheitslistes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing anwesenheitsliste</h1>

  <%= render "form", anwesenheitsliste: @anwesenheitsliste %>

  <%= link_to "Show this anwesenheitsliste", @anwesenheitsliste, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to anwesenheitslistes", anwesenheitslistes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/anwesenheitslistes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Anwesenheitslistes" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Anwesenheitslistes</h1>
    <%= link_to "New anwesenheitsliste", new_anwesenheitsliste_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="anwesenheitslistes" class="min-w-full">
    <% @anwesenheitslistes.each do |anwesenheitsliste| %>
      <%= render anwesenheitsliste %>
      <p>
        <%= link_to "Show this anwesenheitsliste", anwesenheitsliste, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/anwesenheitslistes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New anwesenheitsliste</h1>

  <%= render "form", anwesenheitsliste: @anwesenheitsliste %>

  <%= link_to "Back to anwesenheitslistes", anwesenheitslistes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/anwesenheitslistes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @anwesenheitsliste %>

    <%= link_to "Edit this anwesenheitsliste", edit_anwesenheitsliste_path(@anwesenheitsliste), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to anwesenheitslistes", anwesenheitslistes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this anwesenheitsliste", @anwesenheitsliste, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>