config/routes.rb
Rails.application.routes.draw do
  resources :termins do
    collection do
      get :check
    end
  end
  resources :anwesenheitslistes
  resources :fehlzeits
  resources :veranstaltungs
  resources :moduls
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  # Defines the root path route ("/")
  root "termins#index"
  get 'pages/home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/anwesenheitsliste.rb
class Anwesenheitsliste < ApplicationRecord
  belongs_to :veranstaltung
  has_many :anwesenheitslisten_users
  has_many :users, through: :anwesenheitslisten_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beobachter.rb
class Beobachter < ApplicationRecord
  belongs_to :termin
  def update
    # Logik zur Aktualisierung des Beobachters
  end
end

app/models/fehlzeit.rb
class Fehlzeit < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :veranstaltung
end

app/models/modul.rb
class Modul < ApplicationRecord
  has_many :veranstaltungs
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/termin.rb
class Termin < ApplicationRecord
  belongs_to :veranstaltung
  has_many :beobachters

  validate :termin_zeitraum_frei

  def ergänze_beobachter(beobachter)
    beobachters << beobachter
  end

  def entferne_beobachter(beobachter)
    beobachters.delete(beobachter)
  end

  def benachrichtige_beobachter
    beobachters.each(&:update)
  end

  private

  def termin_zeitraum_frei
    if Termin.exists?(["veranstaltung_id = ? AND ((beginn BETWEEN ? AND ?) OR (ende BETWEEN ? AND ?))", veranstaltung_id, beginn, ende, beginn, ende])
      errors.add(:base, "Ein Termin in diesem Zeitraum existiert bereits.")
    end
  end
end

app/models/termin_vorschlag.rb
class TerminVorschlag
  def initialize(strategy)
    @strategy = strategy
  end

  def generate
    @strategy.generate
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  def ist_verwalter?
    role.rolle == 'Verwalter'
  end

  def ist_dozent?
    role.rolle == 'Dozent'
  end

  def ist_student?
    role.rolle == 'Student'
  end
end

app/models/veranstaltung.rb
class Veranstaltung < ApplicationRecord
  belongs_to :modul
  has_many :fehlzeits
  has_many :anwesenheitslists
  has_many :termine
end

app/controllers/moduls_controller.rb
class ModulsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_modul, only: %i[ show edit update destroy ]

  # GET /moduls or /moduls.json
  def index
    @moduls = Modul.all
  end

  # GET /moduls/1 or /moduls/1.json
  def show
  end

  # GET /moduls/new
  def new
    @modul = Modul.new
  end

  # GET /moduls/1/edit
  def edit
  end

  # POST /moduls or /moduls.json
  def create
    @modul = Modul.new(modul_params)

    respond_to do |format|
      if @modul.save
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully created." }
        format.json { render :show, status: :created, location: @modul }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moduls/1 or /moduls/1.json
  def update
    respond_to do |format|
      if @modul.update(modul_params)
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully updated." }
        format.json { render :show, status: :ok, location: @modul }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moduls/1 or /moduls/1.json
  def destroy
    @modul.destroy!

    respond_to do |format|
      format.html { redirect_to moduls_url, notice: "Modul was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modul
      @modul = Modul.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modul_params
      params.require(:modul).permit(:name, :beschreibung)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fehlzeits_helper.rb
module FehlzeitsHelper
end

app/helpers/moduls_helper.rb
module ModulsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restricted_helper.rb
module RestrictedHelper
end

app/helpers/termine_helper.rb
module TermineHelper
end

app/helpers/termins_helper.rb
module TerminsHelper
end

app/helpers/veranstaltungs_helper.rb
module VeranstaltungsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "ChronoCrew" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body >
<% if user_signed_in? %>
  <%= render 'shared/navbar' %>
  <main class="p-4 sm:ml-64">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </main>
<% else %>
  <%= yield %>
<% end %>
</body>
</html>

app/views/pages/about.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#about</h1>
  <p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/shared/_content1.html.erb
<!-- app/views/pages/_experiments.html.erb -->
<%= turbo_frame_tag "content_frame" do %>
  Ursprünglicher Inhalt
<% end %>

app/views/shared/_content2.html.erb
<%= turbo_frame_tag "content_frame" do %>
Wenn du das sehen kannst, funktioniert Turbo. (Prüfe Konsole auf Fehler)
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-white dark:bg-gray-900 sticky w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600 flex justify-between">
  <div>
    <!-- Suchfeld -->

  </div>
  <div class="bg-gray-300">
    <!--Menüknopf -->
    <%= link_to "Termine", termins_path %> |
    <%= link_to "Module", moduls_path %> |
    <%= link_to "Veranstaltungen", veranstaltungs_path %> |
    <%= link_to "Fehlzeiten", fehlzeits_path %>
  </div>
  <div class="bg-red-300">
    <!-- Accountknopf -->
    Hallo, <%= current_user.email %>
    <% if user_signed_in? %>
      <%= button_to 'Abmelden', destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</nav>

app/views/shared/_schnellleiste.html.erb
<!-- ggf. nachtragen, falls sinnvoll -->