config/routes.rb
Rails.application.routes.draw do
  resources :termins do
    collection do
      get :check
    end
  end
  resources :anwesenheitslistes
  resources :fehlzeits
  resources :veranstaltungs
  resources :moduls
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  # Defines the root path route ("/")
  root "termins#index"
  get 'pages/home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/anwesenheitsliste.rb
class Anwesenheitsliste < ApplicationRecord
  belongs_to :veranstaltung
  has_many :anwesenheitslisten_users
  has_many :users, through: :anwesenheitslisten_users
end

app/models/anwesenheitslisten_users.rb
class AnwesenheitslistenUsers < ApplicationRecord
  belongs_to :anwesenheitsliste
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beobachter.rb
class Beobachter < ApplicationRecord
  belongs_to :termin
  def update
    # Logik zur Aktualisierung des Beobachters
  end
end

app/models/fehlzeit.rb
class Fehlzeit < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :veranstaltung
end

app/models/modul.rb
class Modul < ApplicationRecord
  has_many :veranstaltungs
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/termin.rb
class Termin < ApplicationRecord
  belongs_to :veranstaltung
  has_many :beobachters

  validate :termin_zeitraum_frei

  def ergänze_beobachter(beobachter)
    beobachters << beobachter
  end

  def entferne_beobachter(beobachter)
    beobachters.delete(beobachter)
  end

  def benachrichtige_beobachter
    beobachters.each(&:update)
  end

  private

  def termin_zeitraum_frei
    if Termin.exists?(["veranstaltung_id = ? AND ((beginn BETWEEN ? AND ?) OR (ende BETWEEN ? AND ?))", veranstaltung_id, beginn, ende, beginn, ende])
      errors.add(:base, "Ein Termin in diesem Zeitraum existiert bereits.")
    end
  end
end

app/models/termin_vorschlag.rb
class TerminVorschlag
  def initialize(strategy)
    @strategy = strategy
  end

  def generate
    @strategy.generate
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  def ist_verwalter?
    role.rolle == 'Verwalter'
  end

  def ist_dozent?
    role.rolle == 'Dozent'
  end

  def ist_student?
    role.rolle == 'Student'
  end
end

app/models/veranstaltung.rb
class Veranstaltung < ApplicationRecord
  belongs_to :modul
  has_many :fehlzeits
  has_many :anwesenheitslists
  has_many :termine
end

app/controllers/moduls_controller.rb
class ModulsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_modul, only: %i[ show edit update destroy ]

  # GET /moduls or /moduls.json
  def index
    @moduls = Modul.all
  end

  # GET /moduls/1 or /moduls/1.json
  def show
  end

  # GET /moduls/new
  def new
    @modul = Modul.new
  end

  # GET /moduls/1/edit
  def edit
  end

  # POST /moduls or /moduls.json
  def create
    @modul = Modul.new(modul_params)

    respond_to do |format|
      if @modul.save
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully created." }
        format.json { render :show, status: :created, location: @modul }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moduls/1 or /moduls/1.json
  def update
    respond_to do |format|
      if @modul.update(modul_params)
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully updated." }
        format.json { render :show, status: :ok, location: @modul }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moduls/1 or /moduls/1.json
  def destroy
    @modul.destroy!

    respond_to do |format|
      format.html { redirect_to moduls_url, notice: "Modul was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modul
      @modul = Modul.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modul_params
      params.require(:modul).permit(:name, :beschreibung)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/termins_controller.rb
require_relative '../invokers/termin_invoker'

class TerminsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_termin, only: %i[ show edit update destroy ]
  before_action :set_veranstaltungen, only: %i[new edit create update]


  # GET /termins or /termins.json
  def index
    @termins = Termin.all
  end

  # GET /termins/1 or /termins/1.json
  def show
  end

  # GET /termins/new
  def new
    @termin = Termin.new
  end

  # GET /termins/1/edit
  def edit
  end

  # POST /termins or /termins.json
  def create
    @termin = Termin.new(termin_params)

    respond_to do |format|
      if @termin.save
        format.html { redirect_to termin_url(@termin), notice: "Termin erfolgreich angelegt." }
        format.json { render :show, status: :created, location: @termin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /termins/1 or /termins/1.json
  def update
    respond_to do |format|
      if @termin.update(termin_params)
        format.html { redirect_to termin_url(@termin), notice: "Termin aktualisiert" }
        format.json { render :show, status: :ok, location: @termin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /termins/1 or /termins/1.json
  def destroy
    @termin.destroy!

    respond_to do |format|
      format.html { redirect_to termins_url, notice: "Termin gelöscht." }
      format.json { head :no_content }
    end
  end

  def check
    exists = Termin.exists?(["(beginn <= ? AND ende >= ?)", params[:ende], params[:beginn]])
    if exists
      new_beginn, new_ende = find_alternative(params[:beginn], params[:ende])
      render json: { exists: exists, new_beginn: new_beginn, new_ende: new_ende }
    else
      render json: { exists: exists }
    end
  end

  private

  def find_alternative(beginn, ende)
    loop do
      new_beginn = (beginn.to_time + 5.days).strftime("%Y-%m-%dT%H:%M")
      new_ende = (ende.to_time + 5.days).strftime("%Y-%m-%dT%H:%M")
      break [new_beginn, new_ende] unless Termin.exists?(["(beginn <= ? AND ende >= ?)", new_ende, new_beginn])
      beginn = new_beginn
      ende = new_ende
    end
  end

  def set_termin
    @termin = Termin.find(params[:id])
  end

  def set_veranstaltungen
    @veranstaltungen = Veranstaltung.all
  end

    # Only allow a list of trusted parameters through.
    def termin_params
      params.require(:termin).permit(:bezeichnung, :beginn, :ende, :beschreibung, :veranstaltung_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fehlzeits_helper.rb
module FehlzeitsHelper
end

app/helpers/moduls_helper.rb
module ModulsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restricted_clear_helper.rb
module RestrictedClearHelper
end

app/helpers/restricted_helper.rb
module RestrictedHelper
end

app/helpers/termine_helper.rb
module TermineHelper
end

app/helpers/termins_helper.rb
module TerminsHelper
end

app/helpers/veranstaltungs_helper.rb
module VeranstaltungsHelper
end

app/views/moduls/_form.html.erb
<%= form_with(model: modul, class: "contents") do |form| %>
  <% if modul.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(modul.errors.count, "error") %> prohibited this modul from being saved:</h2>

      <ul>
        <% modul.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :beschreibung %>
    <%= form.text_area :beschreibung, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Speichern", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/moduls/_modul.html.erb
<div id="<%= dom_id modul %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= modul.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Beschreibung:</strong>
    <%= modul.beschreibung %>
  </p>

</div>

app/views/moduls/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Modul bearbeiten</h1>

  <%= render "form", modul: @modul %>

  <%= link_to "Show this modul", @modul, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to moduls", moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/moduls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Moduls" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Module</h1>
    <%= link_to "Neues Modul", new_modul_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="moduls" class="min-w-full">
    <% @moduls.each do |modul| %>
      <%= render modul %>
      <p>
        <%= link_to "Modul anzeigen", modul, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/moduls/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Modul anlegen</h1>

  <%= render "form", modul: @modul %>

  <%= link_to "Zurück zu den Modulen", moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/moduls/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @modul %>

    <%= link_to "Modul bearbeiten", edit_modul_path(@modul), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Zurück zu den Modulen", moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Modul löschen", @modul, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/termins/_form.html.erb
<%= form_with(model: termin, local: true, data: { controller: "termin" }, class: "contents") do |form| %>
  <% if termin.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(termin.errors.count, "error") %> prohibited this termin from being saved:</h2>

      <ul>
        <% termin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :bezeichnung %>
    <%= form.text_field :bezeichnung, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :beginn %>
    <%= form.datetime_local_field :beginn, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full", data: { termin_target: "beginn" } %>
  </div>

  <div class="my-5">
    <%= form.label :ende %>
    <%= form.datetime_local_field :ende, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full", data: { termin_target: "ende" } %>
  </div>

  <div class="my-5">
    <%= form.label :beschreibung %>
    <%= form.text_area :beschreibung, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :veranstaltung_id %>
    <%= form.collection_select :veranstaltung_id, @veranstaltungen, :id, :name, { prompt: "Bitte auswählen" }, { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="inline">
    <%= form.submit "Speichern", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/termins/_termin.html.erb
<div id="<%= dom_id termin %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Bezeichnung:</strong>
    <%= termin.bezeichnung %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Beginn:</strong>
    <%= termin.beginn %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ende:</strong>
    <%= termin.ende %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Beschreibung:</strong>
    <%= termin.beschreibung %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Veranstaltung:</strong>
    <%= termin.veranstaltung_id %>
  </p>

</div>

app/views/termins/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Bearbeite Termin</h1>

  <%= render "form", termin: @termin %>

  <%= link_to "Diesen Termin anzeigen", @termin, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Zurück zu den Terminen", termins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/termins/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Termine" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Termine</h1>
    <%= link_to "Neuer Termin", new_termin_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <table id="termins" class="min-w-full border-collapse">
    <thead>
    <tr>
      <th class="border px-4 py-2">Termin-Details</th>
      <th class="border px-4 py-2">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    <% @termins.each do |termin| %>
      <tr>
        <td class="border px-4 py-2">
          <%= render termin %>
        </td>
        <td class="border px-4 py-2">
          <%= link_to "Termin anzeigen", termin, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/termins/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Neuer Termin</h1>

  <%= render "form", termin: @termin %>

  <%= link_to "Zurück zu den Terminen", termins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/termins/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @termin %>

    <%= link_to "Diesen Termin bearbeiten", edit_termin_path(@termin), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Zurück zu den Terminen", termins_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Termin löschen", @termin, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>