config/routes.rb
Rails.application.routes.draw do
  resources :termins do
    collection do
      get :check
    end
  end
  resources :anwesenheitslistes
  resources :fehlzeits
  resources :veranstaltungs
  resources :moduls
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  # Defines the root path route ("/")
  root "termins#index"
  get 'pages/home'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/veranstaltung.rb
class Veranstaltung < ApplicationRecord
  belongs_to :modul
  has_many :fehlzeits
  has_many :anwesenheitslists
  has_many :termine
end

app/controllers/veranstaltungs_controller.rb
class VeranstaltungsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_veranstaltung, only: %i[ show edit update destroy ]
  before_action :set_module, only: %i[new edit create update]


  # GET /veranstaltungs or /veranstaltungs.json
  def index
    @veranstaltungs = Veranstaltung.all
  end

  # GET /veranstaltungs/1 or /veranstaltungs/1.json
  def show
  end

  # GET /veranstaltungs/new
  def new
    @veranstaltung = Veranstaltung.new
  end

  # GET /veranstaltungs/1/edit
  def edit
  end

  # POST /veranstaltungs or /veranstaltungs.json
  def create
    @veranstaltung = Veranstaltung.new(veranstaltung_params)

    respond_to do |format|
      if @veranstaltung.save
        format.html { redirect_to veranstaltung_url(@veranstaltung), notice: "Veranstaltung erfolgreich erstellt." }
        format.json { render :show, status: :created, location: @veranstaltung }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veranstaltung.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veranstaltungs/1 or /veranstaltungs/1.json
  def update
    respond_to do |format|
      if @veranstaltung.update(veranstaltung_params)
        format.html { redirect_to veranstaltung_url(@veranstaltung), notice: "Veranstaltung was successfully updated." }
        format.json { render :show, status: :ok, location: @veranstaltung }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veranstaltung.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veranstaltungs/1 or /veranstaltungs/1.json
  def destroy
    @veranstaltung.destroy!

    respond_to do |format|
      format.html { redirect_to veranstaltungs_url, notice: "Veranstaltung was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veranstaltung
      @veranstaltung = Veranstaltung.find(params[:id])
    end

  def set_module
    @module = Modul.all
  end

    # Only allow a list of trusted parameters through.
    def veranstaltung_params
      params.require(:veranstaltung).permit(:name, :datum, :beschreibung, :modul_id)
    end
end

app/helpers/veranstaltungs_helper.rb
module VeranstaltungsHelper
end

app/views/veranstaltungs/_form.html.erb
<%= form_with(model: veranstaltung, class: "contents") do |form| %>
  <% if veranstaltung.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 mt-3 font-medium rounded-lg">
      <h2><%= pluralize(veranstaltung.errors.count, "error") %> prohibited this veranstaltung from being saved:</h2>

      <ul>
        <% veranstaltung.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :beschreibung %>
    <%= form.text_area :beschreibung, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :modul_id %>
    <%= form.collection_select :modul_id, @module, :id, :name, { prompt: "Bitte auswählen" }, { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="inline">
    <%= form.submit "Speichern", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/veranstaltungs/_veranstaltung.html.erb
<div id="<%= dom_id veranstaltung %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= veranstaltung.name %>
  </p>


  <p class="my-5">
    <strong class="block font-medium mb-1">Beschreibung:</strong>
    <%= veranstaltung.beschreibung %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Modul:</strong>
    <%= veranstaltung.modul_id %>
  </p>

</div>

app/views/veranstaltungs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Veranstaltung bearbeiten</h1>

  <%= render "form", veranstaltung: @veranstaltung %>

  <%= link_to "Veranstaltung anzeigen", @veranstaltung, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Zurück zu den Veranstaltungen", veranstaltungs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/veranstaltungs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Veranstaltungs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Veranstaltungen</h1>
    <%= link_to "Neue Veranstaltung", new_veranstaltung_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="veranstaltungs" class="min-w-full">
    <% @veranstaltungs.each do |veranstaltung| %>
      <%= render veranstaltung %>
      <p>
        <%= link_to "Zeige Veranstaltung", veranstaltung, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/veranstaltungs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Veranstaltung anlegen</h1>

  <%= render "form", veranstaltung: @veranstaltung %>

  <%= link_to "Zurück zu den Veranstaltungen", veranstaltungs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/veranstaltungs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @veranstaltung %>

    <%= link_to "Veranstaltung bearbeiten", edit_veranstaltung_path(@veranstaltung), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Zurück zu den Veranstaltungen", veranstaltungs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Veranstaltung löschen", @veranstaltung, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>